name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: ./gpu_compile.sh
    - name: run
      run: python3 ./convam_final_test.py
    - name: unit tests
      run: test/test.sh
